Repository squad-parabank-qualitersclub/qa-parabank-cypress, pull requests merged in 2025-03, with the labels that each got.

#4 implementação da funcionalidade criar novo registro através do cypres…
  boasPraticasAutomacao.md
  cypress.config.js
  cypress/e2e/CypressStudio/CriarNovoRegistro.spec.cy.js
Labels: enhancement

#12 implementação da funcionalidade abertura de conta através do cypress …
  cypress/e2e/CypressStudio/AbrirNovaConta.spec.cy.js
Labels: enhancement

#13 foi implementado a funcionalidade 'transferencia de dinheiro' pelo cy…
  cypress/e2e/CypressStudio/TransferenciaDeDinheiro.cy.js
Labels: enhancement

#11 implementação da funcionalidade pagamento de contas através do Cypres…
  cypress/e2e/CypressStudio/CriarNovoRegistro.spec.cy.js
  cypress/e2e/CypressStudio/PagamentoDeContas.spec.cy.js
Labels: enhancement

#23 subindo um cypress.commands.add para substituir o login temporariamente
  cypress/e2e/PageObject/ExemploCommands.spec.cy.js
  cypress/support/commands.js
  cypress/support/pageObject/criarNovoRegistro.pageObject.js
Labels: bug

#27 Implementacao do pageobject da feature de transferencia de dinheiro
  cypress/e2e/CypressStudio/TransferenciaDeDinheiro.spec.cy.js
  cypress/e2e/PageObject/TransferenciaDeDinheiro.spec.cy.js
  cypress/support/elements/transferenciaDeDinheiro.elements.js
  cypress/support/pageObject/transferenciaDeDinheiro.pageObject.js
Labels: duplicate
